# Generated by Django 5.2.6 on 2025-09-18 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbt', '0002_scholarshipapplicant_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scholarshipapplicant',
            name='address',
        ),
        migrations.RemoveField(
            model_name='scholarshipapplicant',
            name='city',
        ),
        migrations.RemoveField(
            model_name='scholarshipapplicant',
            name='country',
        ),
        migrations.RemoveField(
            model_name='scholarshipapplicant',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='scholarshipapplicant',
            name='email',
        ),
        migrations.RemoveField(
            model_name='scholarshipapplicant',
            name='essay',
        ),
        migrations.RemoveField(
            model_name='scholarshipapplicant',
            name='field_of_study',
        ),
        migrations.RemoveField(
            model_name='scholarshipapplicant',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='scholarshipapplicant',
            name='gpa',
        ),
        migrations.RemoveField(
            model_name='scholarshipapplicant',
            name='graduation_year',
        ),
        migrations.RemoveField(
            model_name='scholarshipapplicant',
            name='hobbies',
        ),
        migrations.RemoveField(
            model_name='scholarshipapplicant',
            name='level_of_study',
        ),
        migrations.RemoveField(
            model_name='scholarshipapplicant',
            name='lga',
        ),
        migrations.RemoveField(
            model_name='scholarshipapplicant',
            name='maritalstatus',
        ),
        migrations.RemoveField(
            model_name='scholarshipapplicant',
            name='name',
        ),
        migrations.RemoveField(
            model_name='scholarshipapplicant',
            name='passport_photo',
        ),
        migrations.RemoveField(
            model_name='scholarshipapplicant',
            name='phoneno',
        ),
        migrations.RemoveField(
            model_name='scholarshipapplicant',
            name='previous_awards',
        ),
        migrations.RemoveField(
            model_name='scholarshipapplicant',
            name='referee_contact',
        ),
        migrations.RemoveField(
            model_name='scholarshipapplicant',
            name='referee_name',
        ),
        migrations.RemoveField(
            model_name='scholarshipapplicant',
            name='regdate',
        ),
        migrations.RemoveField(
            model_name='scholarshipapplicant',
            name='result',
        ),
        migrations.RemoveField(
            model_name='scholarshipapplicant',
            name='scholarship_type',
        ),
        migrations.RemoveField(
            model_name='scholarshipapplicant',
            name='school_name',
        ),
        migrations.RemoveField(
            model_name='scholarshipapplicant',
            name='state',
        ),
        migrations.RemoveField(
            model_name='scholarshipapplicant',
            name='zipcode',
        ),
        migrations.AddField(
            model_name='scholarshipapplicant',
            name='scholarship',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applicants', to='cbt.scholarshipprogram'),
        ),
    ]
