# Generated by Django 5.2.6 on 2025-09-18 18:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbt', '0003_remove_scholarshipapplicant_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scholarshipapplicant',
            name='scholarship',
        ),
        migrations.AddField(
            model_name='scholarshipapplicant',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='scholarshipapplicant',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='scholarshipapplicant',
            name='country',
            field=models.CharField(default='Nigeria', max_length=100),
        ),
        migrations.AddField(
            model_name='scholarshipapplicant',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scholarshipapplicant',
            name='email',
            field=models.EmailField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='scholarshipapplicant',
            name='essay',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scholarshipapplicant',
            name='field_of_study',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='scholarshipapplicant',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='scholarshipapplicant',
            name='gpa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='scholarshipapplicant',
            name='graduation_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scholarshipapplicant',
            name='hobbies',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scholarshipapplicant',
            name='level_of_study',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='scholarshipapplicant',
            name='lga',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='scholarshipapplicant',
            name='maritalstatus',
            field=models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='scholarshipapplicant',
            name='name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='scholarshipapplicant',
            name='passport_photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
        migrations.AddField(
            model_name='scholarshipapplicant',
            name='phoneno',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='scholarshipapplicant',
            name='previous_awards',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scholarshipapplicant',
            name='referee_contact',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='scholarshipapplicant',
            name='referee_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='scholarshipapplicant',
            name='regdate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='scholarshipapplicant',
            name='result',
            field=models.FileField(blank=True, null=True, upload_to='results/'),
        ),
        migrations.AddField(
            model_name='scholarshipapplicant',
            name='scholarship_type',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='scholarshipapplicant',
            name='school_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='scholarshipapplicant',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='scholarshipapplicant',
            name='zipcode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
