# Generated by Django 5.2.6 on 2025-09-19 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbt', '0007_scholarshipapplicant_scholarship_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scholarshipapplicant',
            name='scholarship',
        ),
        migrations.AlterField(
            model_name='scholarshipapplicant',
            name='scholarship_type',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
