# Generated by Django 5.2.6 on 2025-09-19 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbt', '0008_remove_scholarshipapplicant_scholarship_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarshipapplicant',
            name='scholarship',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applicants', to='cbt.scholarshipprogram'),
        ),
        migrations.AlterField(
            model_name='scholarshipapplicant',
            name='scholarship_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
