# Generated by Django 5.2.6 on 2025-09-21 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbt', '0009_scholarshipapplicant_scholarship_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarshipapplicant',
            name='community',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='scholarshipapplicant',
            name='wardname',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
