# Generated by Django 5.2.6 on 2025-09-21 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbt', '0010_scholarshipapplicant_community_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarshipapplicant',
            name='idcard',
            field=models.ImageField(blank=True, null=True, upload_to='idcardphotos/'),
        ),
        migrations.AddField(
            model_name='scholarshipapplicant',
            name='lgacert',
            field=models.ImageField(blank=True, null=True, upload_to='lgacertphotos/'),
        ),
    ]
