# Generated by Django 5.2.6 on 2025-09-21 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbt', '0011_scholarshipapplicant_idcard_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcbtanswer',
            name='score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
