from django.urls import path,include
from .views import delete_applicant,reset_applicant_password,view_applicants,register_student,scholarview,edit_course,delete_course,view_courses,question_count,change_password,reset_password,user_logout,course_count,delete_cbt_exam,edit_cbt_exam,view_cbt_exam,delete_scholarship,edit_scholarship,add_cbt_exam,scholarship_list,add_scholarship,setup_scholarship,home,login_user,login_page,register,reg,profile,users_list,update_role,toggle_account_status,remove_user,cbt_setup,add_course,add_question,view_questions,edit_question,delete_question,dd_question,take_exam,student_exams_list,exam_result,edit_applicant,resultdash,exam_leaderboard,export_leaderboard_excel,exam_leaderboardpass,reset_password_view,ward_form_view,scholarrward,upload_question,upload_questions
from rest_framework.routers import DefaultRouter
 
 
urlpatterns = [
    path("",home,name="home"),
    path("home",home,name="home"),
    path("login/",login_page,name="login"),
    path("login_user",login_user,name="login_user"),
    path('register', register, name='register'),
    path('reg', reg, name='reg'),
    path('myprofile', profile, name='profile'),
    path('staff', users_list, name='users_list'),
    path("update-role/<int:user_id>/", update_role, name="update_role"),
    path("toggle-status/<int:user_id>/", toggle_account_status, name="toggle_account_status"),
    path("remove-user/<int:user_id>/", remove_user, name="remove_user"),
    path("cbt-setup/", cbt_setup, name="cbt_setup"),
    path("add-course/", add_course, name="add_course"),
    path('courses/', view_courses, name='view_courses'),
    path("add-question/", add_question, name="add_question"),
    path("course/<int:course_id>/questions/", view_questions, name="view_questions"),
    path("edit/<int:question_id>/", edit_question, name="edit_question"),
    path("question/<int:question_id>/delete/",delete_question, name="delete_question"),
    path("course/<int:course_id>/dd_question/", dd_question, name="dd_question"),
    path("setup_scholarship/", setup_scholarship, name="setup_scholarship"),
    path("add_scholarship/", add_scholarship, name="add_scholarship"),
    path("scholarship_list/", scholarship_list, name="scholarship_list"),
    path("add_cbt_exam/", add_cbt_exam, name="add_cbt_exam"),
    path('scholarship/<int:scholarship_id>/edit/', edit_scholarship, name='edit_scholarship'),
    path('scholarship/<int:scholarship_id>/delete/', delete_scholarship, name='delete_scholarship'),
    path('cbt-exams/', view_cbt_exam, name='view_cbt_exam'),
    path('cbt-exam/add/', add_cbt_exam, name='add_cbt_exam'),
    path('cbt-exam/edit/<int:exam_id>/', edit_cbt_exam, name='edit_cbt_exam'),
    path('cbt-exam/delete/<int:exam_id>/', delete_cbt_exam, name='delete_cbt_exam'),
    path('courses/count/', course_count, name='course-count'),
    path('logout/', user_logout, name='logout'),
    path("reset-password/<int:user_id>/", reset_password, name="reset_password"),
    path("change-password/", change_password, name="change_password"),
    path('courses/question/', question_count, name='question_count'),
    path('courses/edit/<int:course_id>/', edit_course, name='edit_course'),
    path('courses/delete/<int:course_id>/', delete_course, name='delete_course'),
    path('scholarview/', scholarview, name='scholarview'),
    path('register-student/<int:scholarship_id>/', register_student, name='register_student'),
    path("view-applicants/<int:scholarship_id>/", view_applicants, name="view_applicants"),
    path('reset-applicant-password/<str:user_id>/', reset_applicant_password, name='reset_applicant_password'),
    path('delete-applicant/<int:applicant_id>/', delete_applicant, name='delete_applicant'),
    path('cbt/<int:scholarship_id>/take/', take_exam, name='take_exam'),
    path('cbt/exams/', student_exams_list, name='student_exams_list'),
    path('cbt/<int:scholarship_id>/result/', exam_result, name='exam_result'),
    path("applicant/<int:applicant_id>/edit/", edit_applicant, name="edit_applicant"),
    path('resultdash/', resultdash, name='resultdash'),
    path('scholarship/<int:scholarship_id>/leaderboard/<str:wardname>/', exam_leaderboard, name='exam_leaderboard'),
    path('scholarship/<int:scholarship_id>/export_excel/', export_leaderboard_excel, name='export_leaderboard_excel'),
    
    path('scholarship/<int:scholarship_id>/leaderboardpass/', exam_leaderboardpass, name='exam_leaderboardpass'),
    path('reset_password_view', reset_password_view, name='reset_password_view'),
    path('ward_form_view', ward_form_view, name='ward_form_view'),
    path('scholarrward', scholarrward, name='scholarrward'),
    path('course/<int:course_id>/upload/', upload_question, name='upload_question'),
    path('upload_questions/<int:course_id>/upload/', upload_questions, name='upload_questions'),
    
    
]

